### ISSUE TITLE
[DOCUMENTATION] Неконсистентность нумерации списков в README

### ISSUE THREAD

**Issue by stspbu** [aostrouhhov/robot-football#2]
Как мы видим, первый список начинается с нуля, а второй с единицы, что вызывает когнитивный диссонанс у смотрящего.

![image](https://user-images.githubusercontent.com/21951866/80527091-80fa1d00-899c-11ea-8baf-b1ba4b9d7313.png)

**Comment by aostrouhhov** [comment]
Fixed: https://github.com/aostrouhhov/robot-football/commit/8ee66de97973f378b53c0b8305c68e6fc8d92407
