### ISSUE TITLE
Робот идет к мячу по странной траектории

### ISSUE THREAD

**Issue by stspbu** [aostrouhhov/robot-football#4]
1. git checkout master
2. ![image](https://user-images.githubusercontent.com/21951866/80729345-cd666980-8b10-11ea-8cad-ad48c7c30cbc.png)
3. ![image](https://user-images.githubusercontent.com/21951866/80729374-da835880-8b10-11ea-94e4-d1a873642092.png)

Результат:
![image](https://user-images.githubusercontent.com/21951866/80729394-e4a55700-8b10-11ea-86a1-c7a75655eef1.png)

**Comment by aostrouhhov** [comment]
1. `1.5` is too big. `0.15` **is maximum acceptable value** (`BARRIERVELOCITYRANGE = 0.15`). That is why it is not reasonable to run tests in such conditions.
2. The most important thing: kinematics algorithm (`move_to_dot()` function) **is not ideal** by definition. It has `k_ro`, `k_alpha` and `k_beta` constant parameters which can influence movement path and **can show "good" movement in one case and  "bad" in some other case**. At the moment their values are chosen in practical way.
3. Actually, robot moves not to the ball (red circle) but to the position predicted by other algorithm as ball position (yellow circle). As you can see, sometimes **a short-term error occurs and predicted position is far from actual ball position** (yellow circle is far from red circle).

Considering all these statements I can say that such a behaviour is normal. Not a bug.

**Comment by aostrouhhov** [comment]
To clarify: the robot moves **to right direction** (meaning it moves to the specified target dot). It just uses bigger rotation angle (like an airplane) tha we expect in this particular situation. This behaviour comes from, as I said, constant parameters.

**Comment by stspbu** [comment]
Разобрался. 

Мы для перемещения робота юзаем алгоритм, который рассчитывает, что робот в самом конце окажется в позиции мяча при повороте на 0 градусов от оси иксов. Для планирования движения алгоритм мб полезный, но для obstacle avoidance — нет. В ветке vfh сделал альтернативную реализацию, где угол поворота (омега) выбирается не исходя из каких-то ненадежных констант, а на основе того, какова дистанция до цели.
